spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realworlddb
    username: root
    password:

security:
  jwt:
    secret-key: UmVhbHdvcmxkLUFwcGxpY2F0aW9uLVNwcmluZ2Jvb3Q=
    access-expiration-time: 3_600_000
    refresh-expiration-time: 2_592_000_000